### ISSUE TITLE
RW status changes to RO after certain commands

### ISSUE THREAD

**Issue by bouwew** [hansrune/domoticz-contrib#2]
Update: nevermind, by checking the journal I found out that this is caused by a tool that I use to update the /etc/hosts-file. This tool sets the system to rw, then does it's thing and sets the system back to ro.
I need to add some rw/ro-status-checking to the tool.
When either of the below commands is given this tool is called and does its damage.

Hi, after experimenting some more, I noticed that sometimes the RW-status is turned into RO-status after executing certain commands.
Actually, I was setting up the Pi Zero W as an Access Point according to this recipe: 

https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md

Specifically after executing these two commands:
- sudo systemctl restart dhcpcd
- sudo service dnsmasq start

the RW status would change to RO when the prompt would return.
(the RW/RO-status is shown in my prompt)

Would you have any idea why this happens? And how to avoid/fix this, other than executing the rootrw-command to return to RW-status?

**Comment by hansrune** [comment]
Sorry. I cannot reproduce that problem. Are you sure you check root like in:

$ mount | grep " / "
/dev/mmcblk0p2 on / type ext4 (rw,noatime,data=ordered)
